name: Lets Start VcRadio
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@master
        with:
          find: ""
          replace: ""
      - name: Pull All Updates
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'ഇരവും എൻ പകലും'
          commit_options: '--no-verify'
          repository: .
          commit_user_name: Mr-Dark-Prince
          commit_user_email: 73339924+Mr-Dark-Prince@users.noreply.github.com
          commit_author: Mr-Dark-Prince <73339924+Mr-Dark-Prince@users.noreply.github.com>
